export default {
  SWITCH_MONTH: 'SWITCH_MONTH',
  SWITCH_CHEMICAL: 'SWITCH_CHEMICAL',
  SWITCH_FACTORY: 'SWITCH_FACTORY',
  SWITCH_SENSOR: 'SWITCH_SENSOR',
  UPDATE_THRESHOLD: 'UPDATE_THRESHOLD',
  SET_SCT_TOKEN: 'SET_SCT_TOKEN',
  ADD_SCT_CHART: 'ADD_SCT_CHART',
  REMOVE_SCR_CHART: 'REMOVE_SCR_CHART',
  UPDATE_DISTRIBUTE: 'UPDATE_DISTRIBUTE',
  ADD_DIFF_CHART: 'ADD_DIFF_CHART',
  SET_WIND_TOKEN: 'SET_WIND_TOKEN',
  SET_CHEMICAL_TOKEN: 'SET_CHEMICAL_TOKEN',
  SET_TIME_TOKEN: 'SET_TIME_TOKEN',
  SET_CORRELATION_TOKEN: 'SET_CORRELATION_TOKEN'
}
